### ISSUE TITLE
Make YDLidar G4 Work

### ISSUE THREAD

**Issue by LittleD3092** [LittleD3092/refactored-pancake#1]
# Description

The current lidar on burger is not good enough to navigate. I suggest that we buy YDLidar G4, which is the official product page below.

[YDLidar G4](https://www.ydlidar.com/products/view/3.html)

# Screenshots

The picture below shows a screenshot of the product and some specs.

![Screenshot from 2022-10-01 21-14-34](https://user-images.githubusercontent.com/81171284/193411307-1d7b3348-e88e-4023-b130-f94bfe8d58d0.png)

# Tasks

- [x] Discuss whether we should buy it.
- [x] Buy it and wait for the shipping.
- [ ] Install it on our robot.
- [x] Check whether it works.

**Comment by LittleD3092** [comment]
![311003122_1441202609700871_2267244799533990_n](https://user-images.githubusercontent.com/81171284/194487141-32407f50-db65-4515-9766-827aed2cf13b.jpg)

https://user-images.githubusercontent.com/81171284/194487209-1511b71b-6857-4eaf-a155-ec362aea52b7.mp4

YDLidar G4 arrived and tested. But the screws of the support on the robot:

![image](https://user-images.githubusercontent.com/81171284/194487870-787accee-6481-4026-9c93-a08346f1a45b.png)

Require `M2.5` screws. Therefore we either need to 3D print a lidar support or use other method.

**Comment by LittleD3092** [comment]
Update: Lidar support printed.
![image](https://user-images.githubusercontent.com/81171284/197125675-197cf25e-eb61-4b03-9693-8867d6cb6856.png)
