### ISSUE TITLE
Install the Up Squared Pro Series

### ISSUE THREAD

**Issue by LittleD3092** [LittleD3092/refactored-pancake#2]
# Description

We are using raspberry pi 3 now, and I think it can't handle the computation of slam. Therefore, I chose this product that I think is capable of doing this job:

[Up Squared Pro Series - up shop](https://up-shop.org/up-squared-pro-series.html)

Of course, its dimension is just what we needed.

# Screenshots

The picture below is the screenshot of the product page.

![Screenshot from 2022-10-01 21-20-55](https://user-images.githubusercontent.com/81171284/193411518-d47499b7-bd9a-4a31-addf-0e72db1fd86b.png)

# Tasks

- [x] Discuss whether this board is good for our project.
- [x] Buy it and wait for shipping.
- [x] Install it on the robot.
- [x] Check whether it works.

**Comment by LittleD3092** [comment]
# Update

- Ubuntu is installed on the upboard. 
- 1st version support is 3D printed.

# Todos

- [x] Come up with a way to attach power source to upboard.
- [x] Think of a way to set the upboard on turtlebot, so it is secured.
- [x] The copper pillar of the upboard layer should be replaced to longer one.

**Comment by LittleD3092** [comment]
Update: Went to shop to buy the following parts:

1. DC5.5*2.1mm DC插頭
2. 無線網卡 2.4G+5G 藍芽 intel 8265NGW
3. 航模矽膠線
4. 銅柱35+6mm英制(ROHS)

**Comment by LittleD3092** [comment]
Closed: The board can be powered by the power cord and the battery.
