### ISSUE TITLE
The board on the turtlebot does not work

### ISSUE THREAD

**Issue by LittleD3092** [LittleD3092/refactored-pancake#4]
# Description

The board with the battery plugged does not work. However, if an external USB power source is plugged in, it will turn on.

We can't use external USB power source, because it cannot drive the motors.

# Screenshots

![image](https://user-images.githubusercontent.com/81171284/193593072-a2683689-3cab-4408-a81f-339b8c59c01f.png)

# To Reproduce

Simply plug the 12v battery on, you will find out that the board doesn't turn on.

# Tasks

- [ ] Discuss what to do next. Buy a new one? Or find out what's wrong?

**Comment by LittleD3092** [comment]
# Update

Bought the opencr board.

# Todos

- [ ] Wait for shipping.
- [ ] Try it.
- [ ] Install it on turtlebot.

**Comment by LittleD3092** [comment]
Update: The new opencr board isn't coming.
We decided to figure out how to set the opencr up by reading the documents provided by turtlebot github.
[http://turtlebot3.robotis.com/](http://turtlebot3.robotis.com/?fbclid=IwAR3cOm5TNGSB9tmx_v5N17f53qzokDlhFqfMFG14BTxUt9eyMRY9CY0Yu-I)
