### ISSUE TITLE
Integrate Upboard and Opencr

### ISSUE THREAD

**Issue by LittleD3092** [LittleD3092/refactored-pancake#7]
# Description

After #4 #2 is done, we may try to use upboard to control the motors. It should go straight line.

# Tasks

- [ ] Use the upboard to communicate with opencr.
- [ ] Use the upboard to tell opencr to turn on motor.
- [ ] Go straight line using upboard and opencr.
    - [ ] Read encoder.
    - [ ] PID.
    - [ ] Write a ros package for it. Called `base` maybe.
