### ISSUE TITLE
Ready for SSH

### ISSUE THREAD

**Issue by LittleD3092** [LittleD3092/refactored-pancake#9]
# Description

Currently, the upboard need a screen, keyboard and mouse to operate. We need to get ssh server ready.

# Tasks

- [x] Buy m.2 network card
- [x] Setup hotspot. The hotspot should open on startup.
- [x] Setup ssh server.

**Comment by LittleD3092** [comment]
Update: Went to shop to buy the following parts:

1. DC5.5*2.1mm DC插頭
2. 無線網卡 2.4G+5G 藍芽 intel 8265NGW
3. 航模矽膠線
4. 銅柱35+6mm英制(ROHS)

**Comment by LittleD3092** [comment]
Update: The wifi card works perfectly.

**Comment by LittleD3092** [comment]
Update: Now the upboard can open wifi on startup, also you can connect it using ssh.
SSID: `itron-up2`
Wifi Password: `itronitron`

Use `ssh -X itron@10.42.0.1` to connect to upboard.
